### ISSUE TITLE
API response of the selectel_vpc_floatingip_v2 resource contains the loadbalancer field

### ISSUE THREAD

**Issue by v-balanko-formind** [selectel/terraform-provider-selectel#229]
Hi there, We use terraform

1) We create floatingip:

resource "selectel_vpc_floatingip_v2" "floatingip" {
  project_id = var.project_id
  region = var.region
}

2) We assing floatingip to LoadBalancer by Ingress in K8s

3) after that run terraform refresh and got error:
Error: error getting floating IP 'f95e407c-2502-4276-8fa9-ca56324a3d85': json: cannot unmarshal string into Go struct field FloatingIP.floatingip.loadbalancer of type floatingips.LoadBalancer

Here is output of terraform state show module.floatingip.selectel_vpc_floatingip_v2.floatingip:

resource "selectel_vpc_floatingip_v2" "floatingip" {
    floating_ip_address = "<floating_ip_address>" # redacted
    id                  = "f95e407c-2502-4276-8fa9-ca56324a3d85"
    project_id          = "<project_id>" redacted
    region              = "ru-7"
    servers             = []
    status              = "DOWN"
}

Terraform is trying to parse a loadbalancer field from the JSON response. However, based on the output from state file, this field doesn't exist in state. The actual API response of the selectel_vpc_floatingip_v2 resource contains the loadbalancer field and it is a string, it can cause the error

https://registry.terraform.io/providers/selectel/selectel/latest/docs/resources/vpc_floatingip_v2#attributes-reference
To solve this issue need to add field: loadbalancer

**Comment by v-balanko-formind** [comment]
this issue related to https://github.com/selectel/terraform-provider-selectel/issues/27

**Comment by v-balanko-formind** [comment]
https://github.com/selectel/go-selvpcclient/blob/master/selvpcclient/resell/v2/floatingips/schemas.go#L32

**Comment by milkrage** [comment]
Hello, @v-balanko-formind 

The response from the API has been aligned with the selvpcclient schema. 
The problem should be resolved.
