### ISSUE TITLE
Add possibility to change roles of created Service User 

### ISSUE THREAD

**Issue by GRomR1** [selectel/terraform-provider-selectel#246]
Hi there,

Current resources create only Project Administrator role. Please add an attribute to change this

### Affected Resource(s)
Please list the resources as a list, for example:
- selectel_vpc_role_v2
- selectel_vpc_user_v2

<img width="744" alt="image" src="https://github.com/selectel/terraform-provider-selectel/assets/10095462/73adf710-9359-4b40-b145-f18821730f8f">

**Comment by TruePack** [comment]
We are currently working on creating a new role model for users under the control of the terraform provider, which will allow assigning different roles for both service users and account users. The change will be submitted through a new resource, as soon as the change is available we will notify you in this issue.

**Comment by Icerzack** [comment]
Hi @GRomR1! We've recently released a new 5.0.0 version of the Selectel provider, which introduces a new approach to user management. Here's a list of changes:

1. The provider now uses `selectel_iam_serviceuser_v1` resource to manage **service users**. Use `roles` block to assign roles to the service user. More information can be found in the documentation at [this link](https://registry.terraform.io/providers/selectel/selectel/latest/docs/resources/iam_serviceuser_v1)
2. The provider now uses `selectel_iam_user_v1` resource to manage **control panel users**. Also use `roles` block to assign roles to the panel user. More information can be found in the documentation at [this link](https://registry.terraform.io/providers/selectel/selectel/latest/docs/resources/iam_user_v1)

To use the new resources, you need to upgrade to version 5.0.0, you can find the migration guide at [this link](https://registry.terraform.io/providers/selectel/selectel/latest/docs/guides/upgrading_to_version_5). `selectel_vpc_user_v2` and `selectel_vpc_role_v2` resources are deprecated from version 5.0.0.
